---
title: "Bootstrapping"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: github_document
---
### Load packages
```{r load packages and default options, message = FALSE}
# Load packages
library(tidyverse)
library(modelr)
library(p8105.datasets)

# Set seed for reproducibility
set.seed(1)

# Set default figure options
knitr::opts_chunk$set(
  fig.width = 6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Generate a relevant example
```{r generate data}
n_samp = 250

df_sim_const = tibble(
  x = rnorm(n_samp, 1, 1),
  error = rnorm(n_samp, 0, 1),
  y = 2 + 3 * x + error
)

df_sim_non =
  df_sim_const |> 
  mutate(
    error = error * 0.75 * x,
    y = 2 + 3 * x + error
    )

```

```{r look and compare}
df_sim_const |> 
  ggplot(aes(x = x, y = y)) + geom_point()

df_sim_non |> 
  ggplot(aes(x = x, y = y)) + geom_point()
```

Fit some linear models.

```{r}
df_sim_const |> 
  lm(y ~ x, data = _) |> 
  broom::tidy()

df_sim_non |> 
  lm(y ~ x, data = _) |> 
  broom::tidy()
```

## Draw and analyze a bootstrap sample

Start with a lil function
```{r bootstrap function}
boot_samp = function(df){
  sample_frac(df, replace = TRUE)
}
```

```{r prototype code}
df_sim_non |> 
  boot_samp() |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = 0.25) + 
  stat_smooth(method = "lm")
```

## Now iterate this

```{r iterated bootstrapping}
df_bootstrap = tibble(n_strap = 1:2500) |> 
  mutate(
    strap_samp = map(n_strap, \(i) boot_samp(df_sim_non))
  )
```

Now do the `lm` fit.
```{r fit lm on bootstraps}
df_results = 
  df_bootstrap |> 
  mutate(
    models = map(strap_samp, \(df) lm(y ~ x, data = df)),
    model_res = map(models, broom::tidy)
    ) |> 
  select(n_strap, model_res) |> 
  unnest(model_res)
  
```

Try to summarize the results. Get a bootstrap SE

```{r}
df_results |> 
  group_by(term) |> 
  summarize(
    se = sd(estimate)
    )
```

```{r}
df_results |> 
  filter(term == "x") |> 
  ggplot(aes(x = estimate)) + 
  geom_density()
```


Can I construct a confidence interval?
```{r 95% ci}
df_results |> 
  group_by(term) |> 
  summarize(
    ci_lower = quantile(estimate, 0.025),
    ci_upper = quantile(estimate, 0.975)
    )
```


